# Configures the server for Promtail.
server:
  # HTTP server listen port. Default = 80
  http_listen_port: 9080
  # gRPC server listen port. Default = 9095
  grpc_listen_port: 0

# Describes how to save read file offsets to disk.
positions:
  # Location of positions file.
  # Default = "/var/log/positions.yaml"
  filename: "/etc/promtail/positions.yaml"

# Describes how promtail connects to multiple instances of Loki, sending logs to each.
clients:
  # - url: http://localhost:3100/loki/api/v1/push
  - url: "http://edge-grafana-01.homelab:3100/loki/api/v1/push"

# Configures how Promtail can scrape logs from a series of targets using a specified discovery method.
scrape_configs:
  # Name to identify this scrape config in the Promtail UI.
  - job_name: "syslog"
    syslog:
      listen_address: "127.0.0.1:1514"
      listen_protocol: "tcp"
      idle_timeout: "60s"
      label_structured_data: true
      labels:
        job: "syslog"
    relabel_configs:
      - source_labels: ["__syslog_message_hostname"]
        target_label: "host"
      - source_labels: ["__syslog_message_app_name"]
        target_label: "application"
      - source_labels: ["__syslog_message_severity"]
        target_label: "level"
      - source_labels: ["__syslog_message_facility"]
        target_label: "facility"
      - source_labels: ["__syslog_message_msg_id"]
        target_label: "message"
      # - source_labels: ["__syslog_connection_hostname"]
      #   target_label: "connection_hostname"

  # # Name to identify this scrape config in the Promtail UI.
  # - job_name: "system"
  #   # Static targets to scrape.
  #   static_configs:
  #     # Specifying a list of targets and a common label set for them. It is the canonical way to specify static targets in a scrape configuration.
  #     - targets:
  #         - "localhost"
  #       labels:
  #         # A `job` label is fairly standard in prometheus and useful for linking metrics and logs.
  #         job: "varlogs"
  #         # It helps identify logs from this machine vs others.
  #         #host: <yourhost>
  #         host: "${HOSTNAME}"
  #         # The path to load logs from. Can use glob patterns (e.g., /var/log/*.log).
  #         __path__: "/var/log/**/*log"

# Configures global limits for this instance of Promtail
limits_config:
  # When true, enforces rate limiting on this instance of Promtail. Default = false.
  readline_rate_enabled: true

  # The rate limit in log lines per second that this instance of Promtail may push to Loki. Default = 10000.
  readline_rate: 20000

  # When true, exceeding the rate limit causes this instance of Promtail to discard log lines, rather than sending them to Loki.
  # When false, exceeding the rate limit causes this instance of Promtail to temporarily hold off on sending the log lines and retry later.
  readline_rate_drop: false
