# Link: https://grafana.com/docs/loki/latest/send-data/promtail/configuration/

# Configures the server for Promtail.
server:
  # HTTP server listen port. Default = 80
  http_listen_port: 9080
  # gRPC server listen port. Default = 9095
  grpc_listen_port: 0

# Describes how to save read file offsets to disk.
positions:
  # Location of positions file.
  filename: "/etc/promtail/positions.yaml"

# Describes how promtail connects to multiple instances of Loki, sending logs to each.
clients:
  - url: "http://localhost:3100/loki/api/v1/push"

# Configures how Promtail can scrape logs from a series of targets using a specified discovery method.
scrape_configs:
  # Name to identify this scrape config in the Promtail UI.
  - job_name: "syslog"
    syslog:
      # TCP address to listen on. Has the format of "host:port".
      listen_address: "127.0.0.1:1514"
      listen_protocol: "tcp"
      # The idle timeout for tcp syslog connections, default is 120 seconds.
      idle_timeout: "60s"
      # Whether to convert syslog structured data to labels.
      # A structured data entry of [example@99999 test="yes"] would become
      # the label "__syslog_message_sd_example_99999_test" with the value "yes".
      label_structured_data: true
      labels:
        job: "syslog"

    relabel_configs:
      - source_labels: ["__syslog_message_hostname"]
        target_label: "host"
      - source_labels: ["__syslog_message_app_name"]
        target_label: "application"
      - source_labels: ["__syslog_message_severity"]
        target_label: "level"
      - source_labels: ["__syslog_message_facility"]
        target_label: "facility"
      - source_labels: ["__syslog_message_msg_id"]
        target_label: "message"

# Configures global limits for this instance of Promtail
limits_config:
  # When true, enforces rate limiting on this instance of Promtail. Default = false.
  readline_rate_enabled: true

  # The rate limit in log lines per second that this instance of Promtail may push to Loki. Default = 10000.
  readline_rate: 20000

  # When true, exceeding the rate limit causes this instance of Promtail to discard log lines, rather than sending them to Loki.
  # When false, exceeding the rate limit causes this instance of Promtail to temporarily hold off on sending the log lines and retry later.
  readline_rate_drop: false
